### ISSUE TITLE
Also possible for arrow functions?

### ISSUE THREAD

**Issue by peterjuras** [GuillaumeNury/vscode-ts-auto-return-type#2]
Hi!

Thanks for creating this extension, it's really useful!

Would it be also possible to use this for arrow functions? It is currently not doing anything for these functions:

```js
const a = () => "hi"; // should be return type string

express.use((req, res) => { // should be void
  // ...
  // no return statement
});
```

**Comment by GuillaumeNury** [comment]
Hi @peterjuras ! Code is ready, I need to wait a little bit before publishing new version.

**Comment by GuillaumeNury** [comment]
New version is released [HERE](https://marketplace.visualstudio.com/itemdetails?itemName=ebrithil30.vscode-ts-auto-return-type). Thx for your contribution !
